service: cinema-dev-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

  environment:
    RDS_HOST: ${env:RDS_HOST}
    RDS_PORT: ${env:RDS_PORT}
    RDS_USERNAME: ${env:RDS_USERNAME}
    RDS_PASSWORD: ${env:RDS_PASSWORD}
    RDS_DATABASE: ${env:RDS_DATABASE}

functions:
  app:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - dist/**
    - .gitignore
    - .env
